# Default configuration

browser:
  channel: "chrome" # fallback to bundled chromium if not available
  headless_default: false # headed by default
  slow_mo_ms: 300
  default_timeout: 30000
  locale: "en-US"
  timezone: "UTC"
  google_profile_path: "./.cache/google_profile"
  viewport_width: [1200, 1400, 1600]
  viewport_height: [800, 900, 1000]
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/120.0.0.0"

timeouts:
  per_step_seconds: 30
  total_test_minutes: 5
  email_verification_seconds: 120
  retries: 2

proxy: null # http://user:pass@host:port or socks5://user:pass@host:port

cookie_banners:
  reject_selectors:
    - 'button:has-text("Reject")'
    - 'button:has-text("Decline")'
    - '[data-testid="reject-cookies"]'
  accept_selectors:
    - 'button:has-text("Accept")'
    - 'button:has-text("Allow")'
    - '[data-testid="accept-cookies"]'

sso_detection:
  google_selectors:
    - 'button:has-text("Sign in with Google")'
    - 'button:has-text("Weiter mit Google")'
    - 'button:has-text("Google")'
    - 'a:has-text("Google")'
    - '[data-provider="google"]'
    - 'img[alt*="Google"]'
    - 'button[title*="Google"]'
    - '[aria-label*="Google" i]'
    - 'button[aria-label*="Google" i]'
    - 'button:has(svg[aria-label*="Google" i])'
    - 'button:has(svg[title*="Google" i])'
  apple_selectors:
    - 'button:has-text("Sign in with Apple")'
    - '[data-provider="apple"]'
    - 'img[alt*="Apple"]'
  facebook_selectors:
    - 'button:has-text("Facebook")'
    - '[data-provider="facebook"]'
    - 'img[alt*="Facebook"]'
  microsoft_selectors:
    - 'button:has-text("Microsoft")'
    - '[data-provider="microsoft"]'
  github_selectors:
    - 'button:has-text("GitHub")'
    - '[data-provider="github"]'
  twitter_selectors:
    - 'button:has-text("Twitter")'
    - '[data-provider="twitter"]'

discovery_paths:
  login:
    - "/login"
    - "/signin"
    - "/auth/login"
  signup:
    - "/signup"
    - "/register"
    - "/auth/register"

reporting:
  screenshots_full_page_default: true
  redact_pii_default: false
