bild.de:
  login_url: "https://signin.auth.bild.de/login"
  signup_url: "https://signin.auth.bild.de/login" # same entry; page has both
  account_identifier: ".user-email, [data-testid='user-email']"
  email_field: "#identifier"
  password_field: "#password"
  submit_button: "button[data-testid='password-button']"
  sso_detection:
    google_selectors:
      - "button:has-text('Weiter mit Google')"
      - "form#oidc-form button:has-text('Google')"
      - "form#oidc-form button[name='provider']"
