code.org:
  login_url: "https://test-studio.code.org/users/sign_in"
  signup_url: "https://test-studio.code.org/users/sign_up/login_type?user_type=student"

  # Broad account identifier fallbacks
  account_identifier: ".user-email, [data-testid='user-email'], header [aria-label*='account' i] .email, a[href*='/users/'] span, a[href*='/u/'] span"

  # Form fields (cover Rails-style names too)
  email_field: "input[type='email'], input[name='user[email]'], input[name*='email' i], #email, #user_email"
  password_field: "input[type='password'], input[name='user[password]'], #password, #user_password"
  submit_button: "button[type='submit'], input[type='submit'], button:has-text('Sign in'), button:has-text('Sign up'), button:has-text('Continue'), button:has-text('Next')"

  # Optional logout controls
  logout_url: "/users/sign_out"
  profile_menu_selectors:
    - "button[aria-label*='account' i]"
    - "button[aria-label*='profile' i]"
    - "[data-testid='user-menu']"
  logout_selectors:
    - "a:has-text('Sign out')"
    - "button:has-text('Sign out')"
    - "a[href*='sign_out']"
    - "a[href*='logout']"

  # SSO detection (Google + GIS variants)
  sso_detection:
    google_selectors:
      - "button:has-text('Sign in with Google')"
      - "button:has-text('Continue with Google')"
      - "button:has-text('Log in with Google')"
      - "[data-provider='google']"
      - "a[href*='accounts.google.com']"
      - "button[aria-label*='Google' i]"
      - "[aria-label*='Google' i]"
      - ".g_id_signin"
      - "div[id^='g_id_'][role='button']"

studio.code.org:
  login_url: "https://studio.code.org/users/sign_in"
  signup_url: "https://studio.code.org/users/sign_up"
  account_identifier: ".user-email, [data-testid='user-email'], header [aria-label*='account' i] .email, a[href*='/users/'] span, a[href*='/u/'] span"
  email_field: "input[type='email'], input[name='user[email]'], input[name*='email' i], #email, #user_email"
  password_field: "input[type='password'], input[name='user[password]'], #password, #user_password"
  submit_button: "button[type='submit'], input[type='submit'], button:has-text('Sign in'), button:has-text('Sign up'), button:has-text('Continue'), button:has-text('Next')"
  logout_url: "/users/sign_out"
  profile_menu_selectors:
    - "button[aria-label*='account' i]"
    - "button[aria-label*='profile' i]"
    - "[data-testid='user-menu']"
  logout_selectors:
    - "a:has-text('Sign out')"
    - "button:has-text('Sign out')"
    - "a[href*='sign_out']"
    - "a[href*='logout']"
  sso_detection:
    google_selectors:
      - "button:has-text('Sign in with Google')"
      - "button:has-text('Continue with Google')"
      - "button:has-text('Log in with Google')"
      - "[data-provider='google']"
      - "a[href*='accounts.google.com']"
      - "button[aria-label*='Google' i]"
      - "[aria-label*='Google' i]"
      - ".g_id_signin"
      - "div[id^='g_id_'][role='button']"
