datacamp.com:
  # Primary URLs (explicit even though inline forms are supported)
  login_url: "https://www.datacamp.com/users/sign_in"
  signup_url: "https://www.datacamp.com/users/sign_up"

  # Account identity extraction (multiple fallbacks)
  account_identifier: ".user-email, [data-testid='user-email'], [data-qa='user-email'], .dc-user-menu__email, [aria-label*='profile' i] .email, a[href*='/profile'] span, a[href*='/users'] span"

  # Form fields (broad, resilient selectors)
  email_field: "input[type='email'], input[name*='email' i], #email, [autocomplete='email']"
  password_field: "input[type='password'], #password, [autocomplete='current-password']"
  submit_button: "button[type='submit'], input[type='submit'], button:has-text('Sign up'), button:has-text('Log in'), button:has-text('Continue')"

  # Cookie banner handling (site-specific additions on top of defaults)
  cookie_banners:
    reject_selectors:
      - "button:has-text('Reject')"
      - "button:has-text('Decline')"
      - "[data-testid='reject-cookies']"
    accept_selectors:
      - "button:has-text('Accept all cookies')"
      - "button:has-text('Accept Cookies')"
      - "button:has-text('I Accept')"
      - "button:has-text('Accept')"

  # SSO detection (Google only for MVP)
  sso_detection:
    google_selectors:
      - "button:has-text('Continue with Google')"
      - "button:has-text('Sign up with Google')"
      - "button:has-text('Log in with Google')"
      - "[data-provider='google']"
      - "a[href*='accounts.google.com']"
      - "button[aria-label*='Google' i]"
      - "[aria-label*='Google' i]"

www.datacamp.com:
  # Subdomain override (kept same as base; allows future overrides)
  login_url: "https://www.datacamp.com/users/sign_in"
  signup_url: "https://www.datacamp.com/users/sign_up"
  account_identifier: ".user-email, [data-testid='user-email'], [data-qa='user-email'], .dc-user-menu__email, [aria-label*='profile' i] .email, a[href*='/profile'] span, a[href*='/users'] span"
  email_field: "input[type='email'], input[name*='email' i], #email, [autocomplete='email']"
  password_field: "input[type='password'], #password, [autocomplete='current-password']"
  submit_button: "button[type='submit'], input[type='submit'], button:has-text('Sign up'), button:has-text('Log in'), button:has-text('Continue')"
  cookie_banners:
    reject_selectors:
      - "button:has-text('Reject')"
      - "button:has-text('Decline')"
      - "[data-testid='reject-cookies']"
    accept_selectors:
      - "button:has-text('Accept all cookies')"
      - "button:has-text('Accept Cookies')"
      - "button:has-text('I Accept')"
      - "button:has-text('Accept')"
  sso_detection:
    google_selectors:
      - "button:has-text('Continue with Google')"
      - "button:has-text('Sign up with Google')"
      - "button:has-text('Log in with Google')"
      - "[data-provider='google']"
      - "a[href*='accounts.google.com']"
      - "button[aria-label*='Google' i]"
      - "[aria-label*='Google' i]"
