login_url: "/login"
signup_url: "/register"
account_identifier: ".user-email, [data-testid='user-email'], .profile-email"
account_page_url: "/dashboard"
email_field: "input[name='email'], #email"
password_field: "input[name='password'], #password"
submit_button: "button[type='submit'], input[type='submit']"
sso_google:
  - "button:has-text('Sign in with Google')"
  - "[data-provider='google']"
